src/Entity/Betting.php
<?php

namespace App\Entity;

use App\Repository\BettingRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BettingRepository::class)]
class Betting
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    private ?User $idUser = null;

    #[ORM\ManyToOne]
    private Bet $idBet;


    #[ORM\Column]
    private ?int $amount = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isWon = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdUser(): ?User
    {
        return $this->idUser;
    }

    public function setIdUser(?User $idUser): self
    {
        $this->idUser = $idUser;

        return $this;
    }

    public function getBet(): Bet
    {
        return $this->idBet;
    }

    public function setIdBet(?Bet $idBet): self
    {
        $this->idBet = $idBet;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function isIsWon(): ?bool
    {
        return $this->isWon;
    }

    public function setIsWon(?bool $isWon): self
    {
        $this->isWon = $isWon;

        return $this;
    }

}

src/Entity/Points.php
<?php

namespace App\Entity;

use App\Repository\PointsRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PointsRepository::class)]
class Points
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(nullable: true)]
    private ?int $score = null;

    #[ORM\ManyToOne]
    private ?User $idUser = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(onDelete: 'CASCADE')]
    private ?BettingGroup $idBettingGroup = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(?int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->idUser;
    }

    public function setUser(?User $idUser): self
    {
        $this->idUser = $idUser;

        return $this;
    }

    public function getBettingGroup(): ?BettingGroup
    {
        return $this->idBettingGroup;
    }

    public function setBettingGroup(?BettingGroup $idBettingGroup): self
    {
        $this->idBettingGroup = $idBettingGroup;

        return $this;
    }
}

src/Form/BettingType.php
<?php

namespace App\Form;

use App\Entity\Betting;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BettingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('amount')
            ->add('isWon')
            ->add('idUser')
            ->add('idBet')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Betting::class,
        ]);
    }
}

src/Controller/Front/BettingController.php
<?php

namespace App\Controller\Front;
use App\Entity\Betting;
use App\Form\BettingType;
use App\Repository\BettingRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/betting')]
class BettingController extends AbstractController
{
    #[Route('/', name: 'app_betting_index', methods: ['GET'])]
    public function index(BettingRepository $bettingRepository): Response
    {
        return $this->render('betting/index.html.twig', [
            'bettings' => $bettingRepository->findAll(),
        ]);
    }

    #[Route('/my-bettings', name: 'app_betting_my_bettings', methods: ['GET'])]
    public function myBettings(Request $request, BettingRepository $bettingRepository, PaginatorInterface $paginator): Response
    {
        $bettings = $bettingRepository->findBy(['idUser' => $this->getUser()]);
        $events = [];
        foreach ($bettings as $betting) {
            $events[] = $betting->getBet()->getEvent();
        }

        $pagination = $paginator->paginate(
            $bettings,
            $request->query->getInt('page', 1),
            10
        );

        return $this->render('betting/index.html.twig', [
            'bettings' => $pagination,
        ]);
    }

    #[Route('/new', name: 'app_betting_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BettingRepository $bettingRepository): Response
    {
        $betting = new Betting();
        $form = $this->createForm(BettingType::class, $betting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bettingRepository->save($betting, true);

            return $this->redirectToRoute('app_betting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('betting/new.html.twig', [
            'betting' => $betting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_betting_show', methods: ['GET'])]
    public function show(Betting $betting): Response
    {
        return $this->render('betting/show.html.twig', [
            'betting' => $betting,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_betting_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Betting $betting, BettingRepository $bettingRepository): Response
    {
        $form = $this->createForm(BettingType::class, $betting);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bettingRepository->save($betting, true);

            return $this->redirectToRoute('app_betting_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('betting/edit.html.twig', [
            'betting' => $betting,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_betting_delete', methods: ['POST'])]
    public function delete(Request $request, Betting $betting, BettingRepository $bettingRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$betting->getId(), $request->request->get('_token'))) {
            $bettingRepository->remove($betting, true);
        }

        return $this->redirectToRoute('app_betting_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/betting/_delete_form.html.twig
<form method="post" action="{{ path('app_betting_delete', {'id': betting.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ betting.id) }}">
    <button class="btn">Delete</button>
</form>

templates/betting/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/betting/edit.html.twig
<!DOCTYPE html>

<title>Edit Betting</title>

{% block body %}
    <h1>Edit Betting</h1>

    {{ include('betting/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('front_betting_index') }}">back to list</a>

    {{ include('betting/_delete_form.html.twig') }}
{% endblock %}

templates/betting/index.html.twig
{% extends 'base_front.html.twig' %}

{% block title %}Bettings{% endblock %}

{% block body %}
    <!-- This is an example component -->
    <div class=" sm:w-full lg:w-3/4 mx-auto ">

        <div class="p-4  bg-white rounded-lg border shadow-md sm:p-8 ">
            <div class="flex justify-between items-center mb-4">
                <h3 class="text-xl font-bold leading-none text-gray-900 light:text-white">Mes derniers paris</h3>
                <a href="{{ path('front_app_betting_index') }}" class="text-sm font-medium text-blue-600 hover:underline dark:text-blue-500">
                    View all
                </a>
            </div>
            <div class="flow-root">
                <ul role="list" class="divide-gray-200 light:divide-gray-700">
                    {% for betting in bettings %}
                    <li class="mb-2 p-4 border {% if betting.isWon == true %} border-green-400 {% endif %}  {% if betting.isWon == false and betting.isWon != null %} border-red-400 {% endif %}rounded-lg ">
                        <div class="flex items-center space-x-4">
                            <div class="flex-shrink-0">
                                <a href="{{  path('front_app_event_show', {id :betting.bet.event.id} ) }}">
                                    {% if betting.bet.event.coverImage is not null %}
                                <img class="w-8 h-8 rounded-full" src="{{ asset('cover/' ~ betting.bet.event.coverImage) }}" alt="Cover">
                                    {% else %}
                                        <img class="w-8 h-8 rounded-full" src="{{ asset('cover/default.png') }}" alt="Cover">
                                    {% endif %}
                                </a>
                            </div>
                            <div class="flex-1 min-w-0">
                                <p class="text-sm font-medium text-gray-900 truncate light:text-white">
                                    {{ betting.bet.label }}
                                </p>
                                <p class="text-sm text-gray-500 truncate light:text-gray-400">
                                    {{ betting.bet.event.name }}
                                </p>

                            </div>
                            <div class="inline-flex items-center text-base font-semibold text-gray-900 light:text-white">
                                {{ betting.isWon == true ? 'Gagné' : '' }}
                                {{ betting.isWon == false and betting.isWon != null ? 'Perdu' : '' }}
                                {{ betting.isWon == null ? 'En cours' : '' }}
                            </div>
                            <div class="inline-flex items-center text-base font-semibold text-gray-900 light:text-white">
                                {{ betting.amount }} pts
                            </div>
                            {% if  betting.bet.event.bettingGroup is not null %}
                            <div class="flex-shrink-0">
                                <img class="w-8 h-8 rounded-full" src="{{ asset('logos/' ~ betting.bet.event.bettingGroup) }}" alt="Neil image">
                            </div>
                            {% endif %}
                        </div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

    </div>
    <div class="bg-white">

        {{ knp_pagination_render(bettings) }}
    </div>

{% endblock %}

templates/betting/new.html.twig
<!DOCTYPE html>

<title>New Betting</title>

{% block body %}
    <h1>Create new Betting</h1>

    {{ include('betting/_form.html.twig') }}

    <a href="{{ path('front_app_betting_index') }}">back to list</a>
{% endblock %}

templates/betting/show.html.twig
<!DOCTYPE html>

<title>Betting</title>

{% block body %}
    <h1>Betting</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ betting.id }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ betting.amount }}</td>
            </tr>
            <tr>
                <th>IsWon</th>
                <td>{{ betting.isWon ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('front_betting_index') }}">back to list</a>

    <a href="{{ path('front_betting_edit', {'id': betting.id}) }}">edit</a>

    {{ include('betting/_delete_form.html.twig') }}
{% endblock %}